name: Go

on:
  workflow_dispatch:
    inputs:
        url:
          description: 'URL to test'
          required: true
          default: 'https://localhost:8080' 

jobs:
  run: 
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Run
        run: go run ./main.go -- ${{ github.event.inputs.url }}
        
